name: 'Build and Push Docker Image'
description: 'Build Docker image and push to Amazon ECR'
inputs:
  ecr_repository:
    description: 'ECR repository name'
    required: true
  image_tag:
    description: 'Docker image tag to use'
    required: true
  working_directory:
    description: 'Directory containing the Dockerfile'
    default: './webapp'

runs:
  using: 'composite'
  steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Enable advanced Docker features for layer caching
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        context: ${{ inputs.working_directory }}
        push: true
        # Tags for the Docker image. Automatically tags the most recent image as 'latest'
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.image_tag }}
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:latest
        # Use GitHub Actions cache for Docker layers)
        cache-from: type=gha
        cache-to: type=gha,mode=max
